# =========================================================
# RCLONE
# =========================================================

REMOTE="gdrive"
REMOTE_DIR="Backups"

# =========================================================
# ЛОКАЛЬНЫЕ ПАПКИ
# =========================================================

TEMP_DIR="$HOME/Backup/temp"
LOG_DIR="$HOME/Backup/logs"

# =========================================================
# RETENTION
# =========================================================

KEEP_ARCHIVES=30

# =========================================================
# RCLONE НАСТРОЙКИ
# =========================================================

TRANSFERS=4
CHECKERS=8

# =========================================================
# ОБЫЧНАЯ СИНХРОНИЗАЦИЯ
# =========================================================

SYNC_PATHS=(
    "$HOME/Pictures"
)

# =========================================================
# АРХИВИРУЕМЫЕ ПАПКИ
# =========================================================

ARCHIVE_PATHS=(
    "$HOME/Univer/"
)
