# =========================================================
# RCLONE
# =========================================================

REMOTE="gdrive"
REMOTE_DIR="Backups"

# =========================================================
# ЛОКАЛЬНЫЕ ПАПКИ
# =========================================================

TEMP_DIR="$HOME/backup/temp"
LOG_DIR="$HOME/backup/logs"

# =========================================================
# RETENTION
# =========================================================

KEEP_ARCHIVES=30

# =========================================================
# RCLONE НАСТРОЙКИ
# =========================================================

TRANSFERS=4
CHECKERS=8

# =========================================================
# ЗЕРКАЛИРОВАНИЕ
# =========================================================

SYNC_PATHS=(

)

# =========================================================
# АРХИВИРУЕМЫЕ ПАПКИ
# =========================================================

ARCHIVE_PATHS=(
    "$HOME/Obsidian Vaults"
    "$HOME/Games/Saves"
)

# =========================================================
# ОБЫЧНАЯ СИНХРОНИЗАЦИЯ
# =========================================================

COPY_PATHS=(
    "$HOME/Pictures"
    "$HOME/Somethings"
    "$HOME/Univer"
    "$HOME/Games/Factorio/saves"
    "$HOME/.local/share/millennium/plugins/non-steam-playtimes/sessions.json"
)
