REMOTE="gdrive"
REMOTE_DIR="Backups"

TEMP_DIR="$HOME/backup/temp"
LOG_DIR="$HOME/backup/logs"

KEEP_ARCHIVES=30

TRANSFERS=4
CHECKERS=8

SYNC_PATHS=(
    "$HOME/Obsidian Vaults"
)

ARCHIVE_PATHS=(
    "$HOME/Obsidian Vaults"
    "$HOME/Games/Saves"
)

COPY_PATHS=(
    "$HOME/Pictures"
    "$HOME/Somethings"
    "$HOME/Univer"
    "$HOME/Games/Factorio/saves"
    "$HOME/.local/share/millennium/plugins/non-steam-playtimes/sessions.json"
)

