# Формат:
# локальный путь = удаленный путь
# строки, начинающиеся с #, игнорируются

# Папки
/home/ghostik/Documents=gdrive:Documents
/home/ghostik/Univer=gdrive:Univer
/home/ghostik/Somethings=gdrive:Somethings

# Отдельные файлы
#/home/ghostik/Games/factorio/achievements.dat=gdrive:Somethings

# Дополнительные папки
#/home/ghostik/ExtraStuff=gdrive:Somethings
